config firewall policy
    edit 1
        set name "Agentless VPN to Internet"
        set srcintf "ssl.root"
        set dstintf "port1"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set nat enable
        set groups "Agentless_Users"
    next
    edit 3
        set name "AUTO_BLOCKED"
        set srcintf "port1"
        set dstintf "port1"
        set srcaddr "SHUFFLE_BLOCK_LIST"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
    next
    edit 4
        set name "SOC_VPN_Traffic"
        set srcintf "ssl.root"
        set dstintf "port1"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "HTTP" "HTTPS" "RDP" "DNS"
        set logtraffic all
        set nat enable
        set groups "VPN_Users"
    next
end
