name: Deploy Splunk Rules

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Deploy Script
        env:
          SPLUNK_HOST: ${{ secrets.SPLUNK_HOST }}
          SPLUNK_PORT: ${{ secrets.SPLUNK_PORT }}
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
        run: python scripts/deploy.py